### ISSUE TITLE
Support node v16

### ISSUE THREAD

**Issue by mzyil** [trilogy-group/action-npm-install-dependencies#4]
Node v12 is deprecated, it's reaching its EOL

**Comment by mzyil** [comment]
bump @Tantalon

**Comment by Tantalon** [comment]
Happy to take a pull request if you tack it into a related product ticket.

**Comment by mzyil** [comment]
I'd like to work on it, however in the tempo era I'm not allowed to work outside tempo tasks.

**Comment by Tantalon** [comment]
v2 now runs using node16
